//SM3TEST.PRG
//04-08-93 11:12am
//Kopiereg (C) 1993 A van Rensburg
//Program om data te stoor


//*************************************************************************
FUNCTION test()

	open sm3data
	go top

	do case
	case x == 1
		Hallo darr
	case
	endcase


	if c ==2
		Hallo daar
	endif

	if 
	endif


	if
	 dbcloseall()
	 if
		if
			Hallo daar
		endif
		if
			//
		endif

	endif

	endif

	do while !eof()
	enddo

